version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    network_mode: "host"
    ports:
      - "1883:1883"
    volumes:
      - ./conf:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
  
  temperaturesimulator:
    build: ./sourcecode/tempsimulator
    container_name: temperature-simulator
    network_mode: "host"
  
  basestation:
    build: ./sourcecode/basestation
    container_name: basestation
    network_mode: "host"
    ports:
      - "5070:5070"
    volumes:
      - ./output:/output
  
  node01:
    build: ./sourcecode/wsnNode
    container_name: node01
    network_mode: "host"
    environment:
      node_id: "Node01"
